name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - development

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      DB_USER: root
      DB_PASSWORD: root
    strategy:
      fail-fast: true
      matrix:
        cfengine: ["lucee@5", "adobe@2016", "adobe@2018"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Database and Fixtures
        run: |
          sudo /etc/init.d/mysql start
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e 'CREATE DATABASE coolblog;'
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < test-harness/tests/resources/db/coolblog.sql
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup CommandBox
        uses: elpete/setup-commandbox@v1.0.0

      - name: Setup .env For Runner
        run: |
          touch test-harness/.env
          printf "\nDB_HOST=127.0.0.1\n" >> test-harness/.env
          printf "DB_DATABASE=coolblog\n" >> test-harness/.env
          printf "DB_DRIVER=MySQL\n" >> test-harness/.env
          printf "DB_USER=${{ env.DB_USER }}\n" >> test-harness/.env
          printf "DB_PASSWORD=${{ env.DB_PASSWORD }}\n" >> test-harness/.env
          printf "DB_CLASS=com.mysql.cj.jdbc.Driver\n" >> test-harness/.env
          printf "DB_BUNDLEVERSION=8.0.19\n" >> test-harness/.env
          printf "DB_BUNDLENAME=com.mysql.cj\n" >> test-harness/.env
      # - name: Add Hibernate Logging
      #   if: "${{ matrix.cfengine != 'lucee@5' }}"
      #   run: |
      #     # Log4j Hibernate Debug
      #     mkdir -p .engines/acf2016/WEB-INF/cfusion/lib/
      #     mkdir -p .engines/acf2018/WEB-INF/cfusion/lib/
      #     cp build/resources/log4j.properties .engines/acf2016/WEB-INF/cfusion/lib/
      #     cp build/resources/log4j.properties .engines/acf2018/WEB-INF/cfusion/lib/
      - name: Install Dependencies
        run: |
          cd test-harness
          box install
          box install commandbox-cfconfig,commandbox-dotenv,commandbox-docbox

      - name: Start ${{ matrix.cfengine }} Server
        run: |
          cd test-harness
          box server start serverConfigFile="server-${{ matrix.cfengine }}.json" --debug
          curl http://127.0.0.1:60299

      - name: Run Web App Tests
        run: |
          cd test-harness
          mkdir -p tests/results/web
          box package set testbox.runner="http://127.0.0.1:60299/tests/runner.cfm"
          box testbox run --verbose outputFile=tests/results/test-results outputFormats=json,antjunit

      - name: Publish PR Test Reports
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'test-harness/tests/results/**/*.xml'
          summary: true

      - name: Upload Test Results Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coldbox-test-results-${{ matrix.cfengine }}
          path: |
            test-harness/tests/results/**/*

      - name: Failure debugging
        if: ${{ failure() }}
        run: |
          # cat .engines/acf2016/WEB-INF/cfusion/logs/hibernatesql.log
          # cat .engines/acf2018/WEB-INF/cfusion/logs/hibernatesql.log
          cd test-harness
          box server log serverConfigFile="server-${{ matrix.cfengine }}.json"
  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Set Up CommandBox
        uses: elpete/setup-commandbox@v1.0.0

      - name: Install CFFormat
        run: box install commandbox-cfformat

      - name: Run CFFormat
        run: box run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cfformat changes